[package]
name = "soundMixerRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
rodio = "0.20.1"
tui = "0.19"
crossterm = "0.25"
clap = "4.5.38"
